version: "3.8"
services:
  mysql:
    build: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/users.csv:/var/lib/mysql-files/users.csv
      - ./mysql/posts.csv:/var/lib/mysql-files/posts.csv
    ports:
      - 3306:3306

  mysql-copy:
    build: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-volume-copy:/var/lib/mysql
      - ./mysql-copy/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3307:3307

  embulk:
    build: ./embulk
    volumes:
      - ./embulk:/workspace
    stdin_open: true
    tty: true
    working_dir: /workspace
    command: bash -c "digdag scheduler && bash"

volumes:
  mysql-volume:
  mysql-volume-copy:
